apiVersion: v2
name: openbalena
description: openBalena kubernetes Chart
type: application
version: 1.3.4
appVersion: v3.7.2
keywords:
- balena
- openbalena
maintainers:
- name: bartversluijs
  email: bartv@nexelit.io
